In [10]:
import numpy as np

#원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정
R= np.array([[4,np.NaN,np.NaN,2,np.NaN],[np.NaN,5,np.NaN,3,1],[np.NaN,np.NaN,3,4,4],[5,2,1,2,np.NaN]])
num_users,num_items=R.shape
K=3

#P와 Q행렬의 크기를 지정하고 정규분포를 가진 임의의 값으로 입력
np.random.seed(1)
P=np.random.normal(scale=1./K,size=(num_users,K))
Q=np.random.normal(scale=1./K,size=(num_users,K))

In [11]:
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
    error=0
    full_pred_matrix=np.dot(P,Q.T)
    x_non_zero_ind=[non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind=[non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros=full_pred_matrix[x_non_zero_ind,y_non_zero_ind]
    mse=mean_squared_error(R_non_zeros,full_pred_matrix_non_zeros)
    rmse=np.sqrt(mse)
    return rmse

In [ ]:
#R>0인 행 위치, 열 위치, 값을 Non_zeros 리스트에 저장
non_zeros=[(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]
steps=1000
learning_rate=0.01
r_lambda=0.01

for step in range(steps):
    for i,j,r in non_zeros:
        eij= r - np.dot(P[i,:],Q[j,:].T)
        P[i,:]=P[i,:]+learning_rate*(eij*Q[j,:]-r_lambda*P[i,:])
        Q[j,:]=Q[j,:]+learning_rate*(eij*P[i,:]-r_lambda*Q[j,:])
    rmse=get_rmse(R,P,Q,non_zeros)
    if(step%50)==0:
        print("### iteration step:",step,'rmse:',rmse)

In [14]:
pred_matrix=np.dot(P,Q.T)
print('예측행렬:/n', np.round(pred_matrix,3))

예측행렬:/n [[-0.056 -0.163  0.019  0.128]
 [-0.308  0.426  0.342 -0.133]
 [ 0.039 -0.265 -0.08   0.153]
 [-0.316  0.269  0.345  0.043]]
